node {
  git branch: "main", url: "https://github.com/robsonbittencourt/jenkins-pipeline-example"

  stage ('Build Jar') {
    withEnv(["JAVA_HOME=${ tool "java-21" }"]) {
      sh './gradlew clean build -x test'
    }
  }

  stage('Unit Tests') {
    withEnv(["JAVA_HOME=${ tool "java-21" }"]) {
      sh './gradlew test'
    }
  }

  stage ('Sonarqube') {
    withEnv(["JAVA_HOME=${ tool "java-21" }"]) {
      sh './gradlew sonar'
    }
  }

  stage ('Build DEV image') {
    sh 'docker build -t localhost:5000/jenkins-pipeline-example:dev .'
    sh 'docker push localhost:5000/jenkins-pipeline-example:dev'
  }

  stage ('Deploy DEV') {
    sh 'docker rm -f app-dev &>/dev/null && sleep 1 && docker run --name=app-dev -p 8081:8081 --net jenkins-pipeline-example_default -e SPRING_PROFILES_ACTIVE=dev -d localhost:5000/jenkins-pipeline-example:dev'
  }
}