node{

  git branch: "master", url: "file:///var/jenkins_home/git" 

  stage('Test') {
    parallel 'unit': {
        stage('Unit Tests') {
            withEnv(["JAVA_HOME=${ tool "java-8" }", "PATH+MAVEN=${ tool "maven" }/bin:${env.JAVA_HOME}/bin"]) {
                sh "mvn test"
            }
        }
    }, 'integration': {
        stage('Integration Tests') {
            withEnv(["JAVA_HOME=${ tool "java-8" }", "PATH+MAVEN=${ tool "maven" }/bin:${env.JAVA_HOME}/bin"]) {
                sh "mvn verify -Pit-tests"
            }
        }
    }  
  }

  stage ('Sonar') {
    withEnv(["JAVA_HOME=${ tool "java-8" }", "PATH+MAVEN=${ tool "maven" }/bin:${env.JAVA_HOME}/bin"]) {
        sh "mvn sonar:sonar -Dsonar.host.url=http://sonar:9000"
    }
  }
  
  stage ('Build Jar') {
    withEnv(["JAVA_HOME=${ tool "java-8" }", "PATH+MAVEN=${ tool "maven" }/bin:${env.JAVA_HOME}/bin"]) {
        sh "mvn clean package -Dmaven.test.skip=true"
    }
  }

  stage ('Build Image') {
    sh "docker build -t localhost:5000/robsonbittencourt/jenkins-pipeline-example:dsv . ;"
  }

  stage ('Deploy image') {
    sh "docker push localhost:5000/robsonbittencourt/jenkins-pipeline-example:dsv ;"
  }
  
}