node {
  git branch: "main", url: "https://github.com/robsonbittencourt/jenkins-pipeline-example"

  stage ('Build Jar') {
    withEnv(["JAVA_HOME=${ tool "java-21" }"]) {
      sh './gradlew clean build -x test'
    }
  }

  stage('Unit Tests') {
    withEnv(["JAVA_HOME=${ tool "java-21" }"]) {
      sh './gradlew test'
    }
  }

  stage ('Sonarqube') {
    withEnv(["JAVA_HOME=${ tool "java-21" }"]) {
      sh './gradlew sonar'
    }
  }

  stage ('Build and Deploy DSV image') {
    sh 'docker build -t localhost:5000/jenkins-pipeline-example:dsv .'
    sh 'docker push localhost:5000/jenkins-pipeline-example:dsv'
  }

  stage ('Deploy app in DSV') {
    sh 'docker rm -f app-dsv &>/dev/null && sleep 1 && docker run --name=app-dsv -p 8081:8081 --net jenkins-pipeline-example_default -e SPRING_PROFILES_ACTIVE=dsv -d localhost:5000/jenkins-pipeline-example:dsv'
  }
}