node{

  git branch: "master", url: "https://github.com/robsonbittencourt/jenkins-pipeline-example" 

  stage ('Build and Deploy HML image') {
    sh "docker tag robsonbittencourt/jenkins-pipeline-example:dsv robsonbittencourt/jenkins-pipeline-example:hml"
      
    docker.withRegistry("", "registryCredential") {
      sh "docker push robsonbittencourt/jenkins-pipeline-example:hml"
    }    
  }

  stage ('Deploy app in HML') {
    sh "docker rm -f app-hml &>/dev/null && sleep 1 && docker run --name=app-hml -p 8085:8085 --net jenkins-pipeline-example_default -e SPRING_PROFILES_ACTIVE=hml -d robsonbittencourt/jenkins-pipeline-example:hml"
  }

  stage ('UI Tests') {
    withEnv(["JAVA_HOME=${ tool "java-8" }", "PATH+MAVEN=${ tool "maven" }/bin:${env.JAVA_HOME}/bin"]) {
        sh "sleep 5"
        sh "mvn verify -Pui-tests"
    }   
  }

  stage ('Build and Deploy PRD image') {
    sh "docker tag robsonbittencourt/jenkins-pipeline-example:hml robsonbittencourt/jenkins-pipeline-example:prd"

    docker.withRegistry("", "registryCredential") {
      sh "docker push robsonbittencourt/jenkins-pipeline-example:prd"
    }    
  }

  stage ('Deploy app in PRD') {
    sh "docker rm -f app-prd &>/dev/null && sleep 1 && docker run --name=app-prd -p 8090:8090 --net jenkins-pipeline-example_default -e SPRING_PROFILES_ACTIVE=prd -d robsonbittencourt/jenkins-pipeline-example:prd"
  }

}