node{

  git branch: "master", url: "file:///var/jenkins_home/git" 

  stage ('Build and Deploy HML image') {
    sh "docker tag localhost:5000/robsonbittencourt/jenkins-pipeline-example:dsv localhost:5000/robsonbittencourt/jenkins-pipeline-example:hml"
    sh "docker push localhost:5000/robsonbittencourt/jenkins-pipeline-example:hml ;"
  }

  stage ('Deploy app in HML') {
    sh "docker rm -f app-hml"
    sh "docker run -n app-hml -p 8085:8085 localhost:5000/robsonbittencourt/jenkins-pipeline-example:hml"
  }

  stage ('Ui Tests') {
    withEnv(["JAVA_HOME=${ tool "java-8" }", "PATH+MAVEN=${ tool "maven" }/bin:${env.JAVA_HOME}/bin"]) {
        sh "mvn verify -Pui-tests"
    }   
  }

  stage ('Build and Deploy PRD image') {
    sh "docker tag localhost:5000/robsonbittencourt/jenkins-pipeline-example:hml localhost:5000/robsonbittencourt/jenkins-pipeline-example:prd"
    sh "docker push localhost:5000/robsonbittencourt/jenkins-pipeline-example:prd ;"
  }

  stage ('Deploy app in PRD') {
    sh "docker rm -f app-hml"
    sh "docker run --name app-hml localhost:5000/robsonbittencourt/jenkins-pipeline-example:hml"
  }

}